bundlename: chart.extension
filename: chart-extension
bundleversion: 2.0.0.
id: D46B46A9-A0E3-44E1-D972A04AC3A8DC10
label: Chart Extension
luceeCoreVersion: 7.0.0.110
releaseType: server
appendix: -SNAPSHOT
description: Chart Extension to integrate the tag cfchart into Lucee